# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 956)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(800, 40, 411, 116))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radioButton)
        self.ip = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ip.setReadOnly(True)
        self.ip.setObjectName("ip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ip)
        self.vehicle_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.vehicle_name.setReadOnly(True)
        self.vehicle_name.setObjectName("vehicle_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vehicle_name)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(800, 320, 411, 364))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.roll = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.roll.setReadOnly(True)
        self.roll.setObjectName("roll")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roll)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.pitch = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.pitch.setReadOnly(True)
        self.pitch.setObjectName("pitch")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pitch)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.vertical_velocity = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.vertical_velocity.setReadOnly(True)
        self.vertical_velocity.setObjectName("vertical_velocity")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.vertical_velocity)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.flight_time = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.flight_time.setReadOnly(True)
        self.flight_time.setObjectName("flight_time")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.flight_time)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.throttle = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.throttle.setReadOnly(True)
        self.throttle.setObjectName("throttle")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.throttle)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.satcount = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.satcount.setReadOnly(True)
        self.satcount.setObjectName("satcount")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.satcount)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.radio_arm = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.radio_arm.setObjectName("radio_arm")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.radio_arm)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.battery_status = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.battery_status.setReadOnly(True)
        self.battery_status.setObjectName("battery_status")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.battery_status)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.distance_from_home_position = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.distance_from_home_position.setReadOnly(True)
        self.distance_from_home_position.setObjectName("distance_from_home_position")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.distance_from_home_position)
        self.yaw = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.yaw.setReadOnly(True)
        self.yaw.setObjectName("yaw")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.yaw)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizantal_velocity = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.horizantal_velocity.setReadOnly(True)
        self.horizantal_velocity.setObjectName("horizantal_velocity")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.horizantal_velocity)
        self.kamera = QtWidgets.QLabel(self.centralwidget)
        self.kamera.setGeometry(QtCore.QRect(60, 40, 700, 350))
        self.kamera.setText("")
        self.kamera.setPixmap(QtGui.QPixmap("92533e44296e8ab06a367eeff28a0647.png"))
        self.kamera.setObjectName("kamera")
        self.konumlar = QtWidgets.QLabel(self.centralwidget)
        self.konumlar.setGeometry(QtCore.QRect(60, 440, 700, 300))
        self.konumlar.setText("")
        self.konumlar.setPixmap(QtGui.QPixmap("92533e44296e8ab06a367eeff28a0647.png"))
        self.konumlar.setObjectName("konumlar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 770, 721, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buton_arm = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_arm.setObjectName("buton_arm")
        self.gridLayout.addWidget(self.buton_arm, 1, 2, 1, 1)
        self.buton_disarm = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_disarm.setObjectName("buton_disarm")
        self.gridLayout.addWidget(self.buton_disarm, 0, 0, 1, 1)
        self.buton_mode_following = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_mode_following.setObjectName("buton_mode_following")
        self.gridLayout.addWidget(self.buton_mode_following, 1, 1, 1, 1)
        self.buton_mode_kamikaze = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_mode_kamikaze.setObjectName("buton_mode_kamikaze")
        self.gridLayout.addWidget(self.buton_mode_kamikaze, 0, 1, 1, 1)
        self.buton_stop_following = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_stop_following.setObjectName("buton_stop_following")
        self.gridLayout.addWidget(self.buton_stop_following, 1, 0, 1, 1)
        self.buton_emergency_landing = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_emergency_landing.setObjectName("buton_emergency_landing")
        self.gridLayout.addWidget(self.buton_emergency_landing, 0, 2, 1, 1)
        self.buton_return_home_position = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buton_return_home_position.setObjectName("buton_return_home_position")
        self.gridLayout.addWidget(self.buton_return_home_position, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(800, 300, 191, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(60, 750, 131, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(60, 420, 141, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(60, 20, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(800, 20, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Connection:                        "))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.label_7.setText(_translate("MainWindow", "GCS IP:"))
        self.label_6.setText(_translate("MainWindow", "Vehicle Name:"))
        self.label_4.setText(_translate("MainWindow", "RC Connection:"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.ip.setText(_translate("MainWindow", "GCS-IP Label"))
        self.vehicle_name.setText(_translate("MainWindow", "Vehicle Name Label"))
        self.label_10.setText(_translate("MainWindow", "Yaw: "))
        self.label_13.setText(_translate("MainWindow", "Roll: "))
        self.roll.setText(_translate("MainWindow", "Roll Label"))
        self.label_15.setText(_translate("MainWindow", "Pitch:"))
        self.pitch.setText(_translate("MainWindow", "Pitch Label"))
        self.label_9.setText(_translate("MainWindow", "Vertical Velocity:"))
        self.vertical_velocity.setText(_translate("MainWindow", "Vertical Velocit Label"))
        self.label_18.setText(_translate("MainWindow", "Flight Time:"))
        self.flight_time.setText(_translate("MainWindow", "Flight Time Label"))
        self.label_12.setText(_translate("MainWindow", "Throttle:"))
        self.throttle.setText(_translate("MainWindow", "Throttle Label"))
        self.label_17.setText(_translate("MainWindow", "Satcount:"))
        self.satcount.setText(_translate("MainWindow", "Satcount Label"))
        self.label_5.setText(_translate("MainWindow", "Arm:"))
        self.radio_arm.setText(_translate("MainWindow", "RadioButton"))
        self.label_11.setText(_translate("MainWindow", "Battery Status:"))
        self.battery_status.setText(_translate("MainWindow", "Battery Status Label"))
        self.label_16.setText(_translate("MainWindow", "Distance From Home Position:"))
        self.distance_from_home_position.setText(_translate("MainWindow", "Distance From Home Position Label"))
        self.yaw.setText(_translate("MainWindow", "Yaw Label"))
        self.label_8.setText(_translate("MainWindow", "Horizantal Velocity:"))
        self.horizantal_velocity.setText(_translate("MainWindow", "Horizantal Velocity Label"))
        self.buton_arm.setText(_translate("MainWindow", "Arm"))
        self.buton_disarm.setText(_translate("MainWindow", "Disarm"))
        self.buton_mode_following.setText(_translate("MainWindow", "Mode Following"))
        self.buton_mode_kamikaze.setText(_translate("MainWindow", "Mode Kamikaze"))
        self.buton_stop_following.setText(_translate("MainWindow", "Stop Following"))
        self.buton_emergency_landing.setText(_translate("MainWindow", "Emergency Landing"))
        self.buton_return_home_position.setText(_translate("MainWindow", "Return Home Position"))
        self.label_14.setText(_translate("MainWindow", "Vehicle Status Window"))
        self.label_19.setText(_translate("MainWindow", "Siha Kontrol"))
        self.label_20.setText(_translate("MainWindow", "Araç Konumları"))
        self.label_21.setText(_translate("MainWindow", "FPV Kamera"))
        self.label_22.setText(_translate("MainWindow", "General Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

